# Remove the version line - it's obsolete
services:
  postgres-user:
    image: postgres:15
    container_name: rent-postgres-user
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user_user
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_user_data:/var/lib/postgresql/data
    networks:
      - rent-network


  postgres-keycloak:
    image: postgres:15
    container_name: rent-postgres-keycloak
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    ports:
      - "5435:5432"
    volumes:
      - postgres_keycloak_data:/var/lib/postgresql/data
    networks:
      - rent-network

  # Keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: rent-keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-keycloak:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - postgres-keycloak
    networks:
      - rent-network

  # Services
  auth-service:
    build:
      context: ../backend/auth-service
      dockerfile: Dockerfile
    container_name: rent-auth-service
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-user:5432/user_db
      SPRING_DATASOURCE_USERNAME: user_user
      SPRING_DATASOURCE_PASSWORD: ${USER_DB_PASSWORD}
      KEYCLOAK_AUTH_SERVER_URL: ${KEYCLOAK_AUTH_SERVER_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_ADMIN_USER: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "8081:8081"
    depends_on:
      - postgres-user
      - keycloak
    volumes:
      - ./logs/auth-service:/app/logs
    networks:
      - rent-network

volumes:
  postgres_user_data:
  postgres_keycloak_data:

networks:
  rent-network:
    driver: bridge


